version: 0.2
phases:
  install: 
    commands:
    - pip install boto3
    - python --version || python3 --version || true
  build:
    commands:
    - OUTPUT="cooked-stack.json" python ./publish_templates.py
artifacts:
  files:
  - cooked-stack.json
