- priority: 0
  matches:
   - - ${AWS::AccountId}: { "re": ".*" }
  stacks: 
    - iam.json

- priority: 0 # 0 would also be the default.  this is a float! these files don't necessarily conflict.
  matches: # where does this happen
   - - ${AWS::AccountId}: 829378764667
  stacks:
    - iam.json # todo: this should be in default
    - vpc.json
  values:
    org: farrellit-sandbox
  iterators:
    Environment: [ "dev", "qa", "prod" ]
  stack_parameters:
    stack::vpc.json:
      NetworkName: farrellit-sandbox
      Environment: ${Environment}

- priority: 1
  matches: 
  - - ${org}: farrellit-sandbox
    - ${Environment}: dev
  stack_parameters:
    stack::vpc.json:
      VpcCidrBlock: 10.128.0.0/20
      Zone1ExternalCidr: 10.128.0.0/25
      Zone1InternalCidr: 10.128.4.0/23
      Zone1AZ: a
      Zone2ExternalCidr: 10.128.0.128/25
      Zone2InternalCidr: 10.128.6.0/23
      Zone2AZ: b
      Zone3ExternalCidr: 10.128.1.0/25
      Zone3InternalCidr: 10.128.8.0/23
      Zone3AZ: c
      Zone4ExternalCidr: 10.128.1.128/25
      Zone4InternalCidr: 10.128.10.0/23
      Zone4AZ: 
      Zone5ExternalCidr: 10.128.2.0/25
      Zone5InternalCidr: 10.128.12.0/23
      Zone5AZ: 
      Zone6ExternalCidr: 10.128.2.128/25
      Zone6InternalCidr: 10.128.14.0/23
      Zone6AZ: 
      Production: false
